// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARaspdC-wNqVESmfVuJqPCg9wAbomoQrc',
    appId: '1:304771768372:web:36bb2fb7014ebd3ec8aa61',
    messagingSenderId: '304771768372',
    projectId: 'pet-connect-c53f1',
    authDomain: 'pet-connect-c53f1.firebaseapp.com',
    databaseURL: 'https://pet-connect-c53f1-default-rtdb.firebaseio.com',
    storageBucket: 'pet-connect-c53f1.appspot.com',
    measurementId: 'G-XR8CW0ZJEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCDtJsfaiGt43x197C9z2Ys_ASnnheJ5o',
    appId: '1:304771768372:android:ecc3dceace36017fc8aa61',
    messagingSenderId: '304771768372',
    projectId: 'pet-connect-c53f1',
    databaseURL: 'https://pet-connect-c53f1-default-rtdb.firebaseio.com',
    storageBucket: 'pet-connect-c53f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8EFMaSYds3XKaGrZ_2doUmuZotmgt2RQ',
    appId: '1:304771768372:ios:000bec9002808e0bc8aa61',
    messagingSenderId: '304771768372',
    projectId: 'pet-connect-c53f1',
    databaseURL: 'https://pet-connect-c53f1-default-rtdb.firebaseio.com',
    storageBucket: 'pet-connect-c53f1.appspot.com',
    iosBundleId: 'com.petconnect.petConnect',
  );
}
